//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeChallenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public Problem()
        {
            this.Solvings = new HashSet<Solving>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ChallengeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string SampleInput { get; set; }
        public string SampleOutput { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
        public string Attachment { get; set; }
        public int Order { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual ICollection<Solving> Solvings { get; set; }
    }
}
