//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeChallenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solving
    {
        public Solving()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProblemId { get; set; }
        public Nullable<System.DateTime> FirstOpenTime { get; set; }
        public Nullable<System.DateTime> LastOpenTime { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
