//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeChallenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int Id { get; set; }
        public Nullable<int> SolvingId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Content { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Solving Solving { get; set; }
    }
}
